server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Jx1912..
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://120.25.208.32:3306/kindergaten_db?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false

  application:
    name: healther


mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:sqlMapConfig.xml

eureka:
  client:
    fetch-registry: true #是否从eureka服务器获取各个微服务地址
    register-with-eureka: true #是否注册到eureka服务器
    service-url:
      defaultZone: http://localhost:2020/eureka/
